version: '3.8'

services:
  server:
    build:
      context: ./FoodPlanner.Server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  client:
    build:
      context: ./FoodPlanner.Client
      dockerfile: Dockerfile
    ports:
      - "5001:80"
