openapi: 3.0.0
info:
  title: Recipe and Food Planner API
  description: A FastAPI-based API for managing recipes, meal plans, inventory, and shopping lists.
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /recipes:
    post:
      summary: Create a new recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        201:
          description: Recipe created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        400:
          description: Invalid request data
    get:
      summary: Retrieve all recipes
      responses:
        200:
          description: A list of recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'

  /recipes/{recipe_id}:
    get:
      summary: Retrieve a specific recipe by ID
      parameters:
        - in: path
          name: recipe_id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Recipe found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        404:
          description: Recipe not found
    put:
      summary: Update a specific recipe by ID
      parameters:
        - in: path
          name: recipe_id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        200:
          description: Recipe updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        400:
          description: Invalid request data
        404:
          description: Recipe not found
    delete:
      summary: Delete a specific recipe by ID
      parameters:
        - in: path
          name: recipe_id
          schema:
            type: string
          required: true
      responses:
        204:
          description: Recipe deleted successfully
        404:
          description: Recipe not found

components:
  schemas:
    Recipe:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        description:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        instructions:
          type: array
          items:
            $ref: '#/components/schemas/Instruction'
        nutritionInfo:
          $ref: '#/components/schemas/NutritionInfo'
        tags:
          type: array
          items:
            type: string
        prepTime:
          type: integer
        cookTime:
          type: integer
        servings:
          type: integer

    Ingredient:
      type: object
      properties:
        name:
          type: string
        quantity:
          type: number
        unit:
          type: string

    Instruction:
      type: object
      properties:
        stepNumber:
          type: integer
        description:
          type: string
NutritionInfo:
  type: object
  properties:
    calories:
      type: number
    protein:
      type: number
    fat:
      type: number
    carbohydrates:
      type: number
    fiber:
      type: number
    sugar:
      type: number
    sodium:
      type: number

