version: '3.8'

services:

  recipemicroservice:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=recipedb;User=sa;Password=Your_password123;
      - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=Your_password123
      - MYSQL_DATABASE=recipedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=Your_password123
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
